name: Django CI with Docker

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Create .env file from Secrets
      run: |
        ENV_FILE=".env"
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> "$ENV_FILE"
        echo "DB_USER=${{ secrets.DB_USER }}" >> "$ENV_FILE"
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> "$ENV_FILE"
        echo "DB_HOST=db" >> "$ENV_FILE"
        echo "DB_PORT=5432" >> "$ENV_FILE"
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> "$ENV_FILE"
        echo "DEBUG=False" >> "$ENV_FILE"
        echo "VK_TOKEN=${{ secrets.VK_TOKEN }}" >> "$ENV_FILE"

    - name: Build and Run Docker Containers
      run: docker compose up -d

    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Run Django Tests
      run: |
        docker compose exec -T web python manage.py test

    - name: Show Docker logs on failure
      if: failure()
      run: docker compose logs

    - name: Shutdown Docker
      if: always()
      run: docker compose down